# -*- coding: utf-8 -*-
COUNTRIES = {
  "North America" => [
                      "Antigua and Barbuda",
                      "Aruba",
                      "Bahamas",
                      "Barbados",
                      "Belize",
                      "Bermuda",
                      "Canada",
                      "Cayman Islands",
                      "Cook Islands",
                      "Costa Rica",
                      "Cuba",
                      "Dominica",
                      "Dominican Republic",
                      "El Salvador",
                      "Grenada",
                      "Guatemala",
                      "Haiti",
                      "Honduras",
                      "Jamaica",
                      "Mexico",
                      "Netherlands Antilles",
                      "Nicaragua",
                      "Panama",
                      "Puerto Rico",
                      "Saint Kitts and Nevis",
                      "Saint Lucia",
                      "Saint Vincent and the Grenadines",
                      "Trinidad and Tobago",
                      "United States",
                      "Virgin Islands, British",
                      "Virgin Islands, U.S."
                     ],

  "South America" => [
                      "Argentina",
                      "Bolivia",
                      "Brazil",
                      "Chile",
                      "Colombia",
                      "Ecuador",
                      "Guyana",
                      "Paraguay",
                      "Peru",
                      "Suriname",
                      "Uruguay",
                      "Venezuela"
                     ],

  "Europe" => [
               "Albania",
               "Andorra",
               "Armenia",
               "Austria",
               "Azerbaijan",
               "Belarus",
               "Belgium",
               "Bosnia and Herzegovina",
               "Bulgaria",
               "Croatia",
               "Cyprus",
               "Czech Republic",
               "Denmark",
               "Estonia",
               "Faroe Islands",
               "Finland",
               "France",
               "Georgia",
               "Germany",
               "Greece",
               "Hungary",
               "Iceland",
               "Ireland",
               "Italy",
               "Latvia",
               "Liechtenstein",
               "Lithuania",
               "Luxembourg",
               "Macedonia",
               "Malta",
               "Moldova",
               "Monaco",
               "Montenegro",
               "Netherlands",
               "Norway",
               "Poland",
               "Portugal",
               "Romania",
               "San Marino",
               "Serbia",
               "Slovakia",
               "Slovenia",
               "Spain",
               "Sweden",
               "Switzerland",
               "Ukraine",
               "United Kingdom",
               "Vatican City"
              ],

  "Asia" => [
             "Afghanistan",
             "Bahrain",
             "Bangladesh",
             "Bhutan",
             "Brunei Darussalam",
             "Myanmar",
             "Cambodia",
             "China",
             "East Timor",
             "Hong Kong",
             "India",
             "Indonesia",
             "Iran",
             "Iraq",
             "Israel",
             "Japan",
             "Jordan",
             "Kazakhstan",
             "North Korea",
             "South Korea",
             "Kuwait",
             "Kyrgyzstan",
             "Laos",
             "Lebanon",
             "Malaysia",
             "Maldives",
             "Mongolia",
             "Nepal",
             "Oman",
             "Pakistan",
             "Palestine",
             "Philippines",
             "Qatar",
             "Russia",
             "Saudi Arabia",
             "Singapore",
             "Sri Lanka",
             "Syria",
             "Taiwan",
             "Tajikistan",
             "Thailand",
             "Turkey",
             "Turkmenistan",
             "United Arab Emirates",
             "Uzbekistan",
             "Vietnam",
             "Yemen"
            ],

  "Oceania" => [
                "Australia",
                "Fiji",
                "Kiribati",
                "Marshall Islands",
                "Micronesia",
                "Nauru",
                "New Zealand",
                "Palau",
                "Papua New Guinea",
                "Samoa",
                "Solomon Islands",
                "Tonga",
                "Tuvalu",
                "Vanuatu"
               ],

  "Africa" => [
               "Algeria",
               "Angola",
               "Benin",
               "Botswana",
               "Burkina Faso",
               "Burundi",
               "Cameroon",
               "Cape Verde",
               "Central African Republic",
               "Chad",
               "Comoros",
               "Democratic Republic of the Congo",
               "Republic of the Congo",
               "Djibouti",
               "Egypt",
               "Equatorial Guinea",
               "Eritrea",
               "Ethiopia",
               "Gabon",
               "Gambia",
               "Ghana",
               "Gibraltar",
               "Guinea",
               "Guinea-Bissau",
               "Côte d'Ivoire",
               "Kenya",
               "Lesotho",
               "Liberia",
               "Libya",
               "Madagascar",
               "Malawi",
               "Mali",
               "Mauritania",
               "Mauritius",
               "Morocco",
               "Mozambique",
               "Namibia",
               "Niger",
               "Nigeria",
               "Rwanda",
               "Sao Tome and Principe",
               "Senegal",
               "Seychelles",
               "Sierra Leone",
               "Somalia",
               "South Africa",
               "Sudan",
               "Swaziland",
               "United Republic of Tanzania",
               "Togo",
               "Tunisia",
               "Uganda",
               "Zambia",
               "Zimbabwe"
              ]
}
